version: '3.8'
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    working_dir: /var/www/html/
    volumes:
      - ./app/src:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: my_database
      MYSQL_USER: Eduardo172732
      MYSQL_PASSWORD: Eduardo172732
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on: 
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db